with-expecter: True
dir: tests/mocks/{{.InterfaceDirRelative}}
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
all: True
packages:
  github.com/openearthplatforminitiative/client-registration-api/keycloak:

