apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-registration-api
  namespace: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: deployment/kubernetes/
    repoURL: https://github.com/openearthplatforminitiative/client-registration-api
    targetRevision: Issue-253-Simplest-possible-API
  syncPolicy:
    automated:
      prune: true
