apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-registration-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: client-registration-api
  template:
    metadata:
      labels:
        app: client-registration-api
#      annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/port: "8080"
#        prometheus.io/path: "/metrics"
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/client-registration-api:latest
          name: client-registration-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: API_ROOT_PATH
              value: "/client-registration"
            - name: VERSION
              value: "latest"
            - name: API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: openepi-apps-config
                  key: api_domain
            - name: KC_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: kc_url
            - name: KC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: admin_password
            - name: KC_USER_REALM
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: user_auth_realm
---
apiVersion: v1
kind: Service
metadata:
  name: client-registration-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: auth
      port: 4181
      targetPort: 4181
  selector:
    app: client-registration-api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-client-registration
spec:
  stripPrefix:
    prefixes:
      - /client-registration
    forceSlash: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: client-registration-api
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/client-registration`) && !PathPrefix(`/client-registration/metrics`)
    services:
    - kind: Service
      name: client-registration-api
      port: 80
    middlewares:
    - name: traefikmiddleware-cors-for-internal-apps@kubernetescrd
    - name: traefikmiddleware-jwt@kubernetescrd
    - name: stripprefix-client-registration
